// 2026 F1 grid as chibi animals. Numbers from the FIA entry list.
// Each driver's animal, prop and expression nods to something fans affectionately know them for.
// Helmet colours are approximate; no team or sponsor logos.

export const TEAMS = {
  mclaren:  { name: "McLaren",      suit: "#ff8000", panel: "#1b1b1b", pipe: "#47c7fc" },
  ferrari:  { name: "Ferrari",      suit: "#e8002d", panel: "#8f0019", pipe: "#fff200" },
  redbull:  { name: "Red Bull",     suit: "#1e2a5a", panel: "#e3101b", pipe: "#ffc906" },
  mercedes: { name: "Mercedes",     suit: "#16191d", panel: "#00a19c", pipe: "#2ee6d6" },
  aston:    { name: "Aston Martin", suit: "#006f62", panel: "#0b3d36", pipe: "#cedc00" },
  alpine:   { name: "Alpine",       suit: "#0078c1", panel: "#ff87bc", pipe: "#ffffff" },
  williams: { name: "Williams",     suit: "#0a2d6e", panel: "#37bedd", pipe: "#ffffff" },
  rb:       { name: "Racing Bulls", suit: "#f4f4f4", panel: "#1634cb", pipe: "#e3101b" },
  haas:     { name: "Haas",         suit: "#ededed", panel: "#da291c", pipe: "#222222" },
  audi:     { name: "Audi",         suit: "#2b2b2b", panel: "#c9cdd1", pipe: "#f50537" },
  cadillac: { name: "Cadillac",     suit: "#1a1a1a", panel: "#f4f4f4", pipe: "#c8a45d" },
};

// species: cat | lion | dog | koala | beaver | kiwi | bear
// mood: open | smile | grin | fierce | chill | wink | sparkle
// prop: headset | notes | stopwatch | plan | football | hearts | kitten | shades | lplate | trophy | shield
export const DRIVERS = [
  { code: "NOR", num: 1,  name: "Lando Norris",      team: "mclaren",  species: "cat",    mood: "grin",    prop: "headset",
    fur: "#ff9a3c", dark: "#d9661a", stripes: true, eye: "#3fa7ff",
    helmet: ["#e9ff3d", "#2f6bff", "#ff3fa4"], note: "Orange tabby with his gaming headset" },
  { code: "PIA", num: 81, name: "Oscar Piastri",     team: "mclaren",  species: "koala",  mood: "chill",
    fur: "#9aa0a8", dark: "#6f757d", eye: "#5b4a3a",
    helmet: ["#f4f4f4", "#ff8000", "#1c3fa8"], note: "Unflappable Aussie koala" },
  { code: "LEC", num: 16, name: "Charles Leclerc",   team: "ferrari",  species: "cat",    mood: "smile",   prop: "notes",
    fur: "#33333d", dark: "#1c1c22", muzzle: "#4a4a56", eye: "#7ad1a8",
    helmet: ["#e8002d", "#ffffff", "#1c3fa8"], note: "Black cat who composes piano pieces" },
  { code: "HAM", num: 44, name: "Lewis Hamilton",    team: "ferrari",  species: "dog",    mood: "open",
    fur: "#c9a27a", dark: "#8a6440", muzzle: "#f1e1c8", eye: "#5b3a1e",
    helmet: ["#fff200", "#e8002d", "#111111"], note: "Bulldog, after his dog Roscoe" },
  { code: "VER", num: 3,  name: "Max Verstappen",    team: "redbull",  species: "lion",   mood: "fierce",
    fur: "#f0b45a", dark: "#c98a2e", mane: "#b5651d", eye: "#4f8fe0",
    helmet: ["#1b2a6b", "#ff6a00", "#e3101b"], note: "Lion cub, a long-time helmet motif" },
  { code: "HAD", num: 6,  name: "Isack Hadjar",      team: "redbull",  species: "cat",    mood: "sparkle",
    fur: "#f2efe9", dark: "#c9bfb0", eye: "#e0a030",
    helmet: ["#1e2a5a", "#ffffff", "#2ec4ff"], note: "Bright-eyed young cat" },
  { code: "RUS", num: 63, name: "George Russell",    team: "mercedes", species: "cat",    mood: "smile",   prop: "stopwatch",
    fur: "#c9ced6", dark: "#8e96a3", stripes: true, eye: "#2ec4b6",
    helmet: ["#2ee6d6", "#16191d", "#ffffff"], note: "Silver tabby, 'Mr Saturday' with his stopwatch" },
  { code: "ANT", num: 12, name: "Kimi Antonelli",    team: "mercedes", species: "cat",    mood: "sparkle",
    fur: "#f7d9b0", dark: "#d9a86b", eye: "#4f8fe0",
    helmet: ["#16191d", "#2ee6d6", "#ff3d3d"], note: "Wide-eyed kitten" },
  { code: "ALO", num: 14, name: "Fernando Alonso",   team: "aston",    species: "cat",    mood: "wink",    prop: "plan",
    fur: "#a8784a", dark: "#6e4b2a", stripes: true, eye: "#7ad1a8",
    helmet: ["#1c4fd8", "#ffd400", "#e3101b"], note: "Wise old tabby with El Plan" },
  { code: "STR", num: 18, name: "Lance Stroll",      team: "aston",    species: "beaver", mood: "smile",
    fur: "#8b5a2b", dark: "#5e3a17", muzzle: "#c9a07a", eye: "#3b2a1a",
    helmet: ["#ffffff", "#006f62", "#e3101b"], note: "Canadian beaver" },
  { code: "GAS", num: 10, name: "Pierre Gasly",      team: "alpine",   species: "cat",    mood: "grin",    prop: "football",
    fur: "#f2f2f2", dark: "#9aa0a8", patches: true, eye: "#3fa7ff",
    helmet: ["#ffffff", "#0078c1", "#ff87bc"], note: "Football-mad cat" },
  { code: "COL", num: 43, name: "Franco Colapinto",  team: "alpine",   species: "cat",    mood: "sparkle", prop: "hearts",
    fur: "#f2c46b", dark: "#c99a3a", eye: "#3b7ddd",
    helmet: ["#74c0fc", "#ffffff", "#ffd400"], note: "Fan favourite, hearts everywhere" },
  { code: "ALB", num: 23, name: "Alex Albon",        team: "williams", species: "cat",    mood: "grin",    prop: "kitten",
    fur: "#efe2cc", dark: "#6b4f3a", mask: true, eye: "#3fa7ff",
    helmet: ["#0a2d6e", "#ffffff", "#e3101b"], note: "Cat dad with a kitten on his head" },
  { code: "SAI", num: 55, name: "Carlos Sainz",      team: "williams", species: "cat",    mood: "smile",   prop: "shades",
    fur: "#8d8f96", dark: "#5a5c62", stripes: true, eye: "#7ad1a8",
    helmet: ["#e3101b", "#ffd400", "#1c3fa8"], note: "Smooth Operator in sunglasses" },
  { code: "LAW", num: 30, name: "Liam Lawson",       team: "rb",       species: "kiwi",   mood: "fierce",
    fur: "#8a6a45", dark: "#5e4529", eye: "#3b2a1a",
    helmet: ["#111111", "#ffffff", "#1634cb"], note: "Feisty Kiwi" },
  { code: "LIN", num: 41, name: "Arvid Lindblad",    team: "rb",       species: "cat",    mood: "sparkle", prop: "lplate",
    fur: "#e6c39a", dark: "#b8915f", eye: "#4f8fe0",
    helmet: ["#ff9933", "#ffffff", "#1634cb"], note: "The rookie, learner plate on" },
  { code: "OCO", num: 31, name: "Esteban Ocon",      team: "haas",     species: "cat",    mood: "smile",
    fur: "#2b2b33", dark: "#16161b", muzzle: "#f4f4f4", tuxedo: true, eye: "#e0a030",
    helmet: ["#1c3fa8", "#ffffff", "#e3101b"], note: "Dapper tuxedo cat" },
  { code: "BEA", num: 87, name: "Oliver Bearman",    team: "haas",     species: "bear",   mood: "grin",
    fur: "#a0673a", dark: "#6e4424", muzzle: "#e3c39d", eye: "#3b2a1a",
    helmet: ["#ffffff", "#da291c", "#1c3fa8"], note: "Bear cub, naturally" },
  { code: "HUL", num: 27, name: "Nico Hülkenberg",   team: "audi",     species: "cat",    mood: "grin",    prop: "trophy",
    fur: "#d8c08a", dark: "#a88a4e", eye: "#3fa7ff",
    helmet: ["#f4f4f4", "#111111", "#f50537"], note: "Proud owner of a Lego trophy" },
  { code: "BOR", num: 5,  name: "Gabriel Bortoleto", team: "audi",     species: "cat",    mood: "sparkle",
    fur: "#f3e3c3", dark: "#b08a55", patches: true, eye: "#2fa86b",
    helmet: ["#ffd400", "#009c3b", "#1c3fa8"], note: "Bright young cat" },
  { code: "PER", num: 11, name: "Sergio Pérez",      team: "cadillac", species: "cat",    mood: "smile",   prop: "shield",
    fur: "#6b4a32", dark: "#45301f", muzzle: "#c9a27a", eye: "#e0a030",
    helmet: ["#006847", "#ffffff", "#ce1126"], note: "The Minister of Defence" },
  { code: "BOT", num: 77, name: "Valtteri Bottas",   team: "cadillac", species: "cat",    mood: "chill",   mullet: true, tache: true,
    fur: "#b9bcc4", dark: "#7d6a55", eye: "#7ad1a8",
    helmet: ["#f4f4f4", "#1e5bd8", "#c8a45d"], note: "Mullet, moustache, unbothered" },
];
